version: "3"
services:
  socket-app:
    image: node:18-alpine
    working_dir: /
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
    ports:
      - "9010:9010"
    command: ["sh", "-c", "npm install && npm start"]
